In [74]:
import numpy as np
print("numpy is imported!")

numpy is imported!


In [75]:
lst=list(range(1,25))
print("list:",lst)
print(type(lst))
arr=np.array(lst)
print("array:",arr)
print(type(arr))

list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
<class 'list'>
array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
<class 'numpy.ndarray'>


list stored different kinds of datatypes where as array contains similar datatypes.

In [76]:
# creating array using np:
arr1=np.array([1,3,4,6])
arr1

array([1, 3, 4, 6])

In [77]:
# list
l=[3,34,5,2]
print(l)

[3, 34, 5, 2]


In [78]:
# arrange() function
arr=np.arange(1,25)
print(arr)
# 1 D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [79]:
# 2D array
arr=np.array([[2,3,5],[4,5,6]])
print(arr)
# to print the dimension of the arrays
print(arr.ndim)

[[2 3 5]
 [4 5 6]]
2


In [80]:
# 3 D array
arr=np.array([[[2,3,4],[4,5,6],[6,7,8]]])
print(arr)
# to print the dimension of the array
print(arr.ndim)

[[[2 3 4]
  [4 5 6]
  [6 7 8]]]
3


In [81]:
arr4=np.array([[[2,3,4,8],[4,5,6,8],[6,7,8,3]],[[2,3,4,6],[4,6,7,6],[6,7,8,9]]])
arr4

array([[[2, 3, 4, 8],
        [4, 5, 6, 8],
        [6, 7, 8, 3]],

       [[2, 3, 4, 6],
        [4, 6, 7, 6],
        [6, 7, 8, 9]]])

In [82]:
arr4.ndim

3

In [83]:

# zeros functions:to print the zero matrix
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [84]:
# ones functions
arr=np.ones((3,4))
print(arr)
print(arr.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [85]:
# linspace functions:create a array with equal difference btw the given number
arr=np.linspace(1,10,5)
print(arr)
print(arr.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [ ]:
# reshape is used to convert the dimension of the array from 1d array to 2d array
rs=np.linspace(1,10,5).reshape(5,1)
rs
print(rs.ndim)

2


In [99]:
arr=np.arange(0,30).reshape(2,15)
print(arr)
print(arr.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
2


In [100]:
arr.shape

(2, 15)

# 3 D array conversion 

In [104]:
arr=np.arange(0,30).reshape(5,6,1)
print(arr)
print(arr.ndim)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]

 [[24]
  [25]
  [26]
  [27]
  [28]
  [29]]]
3


In [111]:
arr=np.arange(0,30).reshape(3,5,2)
print(arr)
print("dimension:",arr.ndim)
print("shape:",arr.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
dimension: 3
shape: (3, 5, 2)


In [115]:
# random initialization
arr=np.random.randint(1,50)
# 1-50 is the range 
# by default 1 
print(arr)

9


In [125]:
arr=np.random.randint(1,50,3)
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)
# 1 D array


[16 42 28]
1


In [126]:
arr=np.random.randint(1,5,(3,3))
# coverting to 2 dim
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)

[[2 3 1]
 [2 2 3]
 [4 1 2]]
2


In [127]:
arr=np.random.randint(1,5,(3,3,3))
# coverting to 3 Dimension
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)

[[[2 1 1]
  [2 4 1]
  [1 3 1]]

 [[4 3 4]
  [4 1 2]
  [3 1 2]]

 [[2 2 4]
  [1 3 1]
  [1 1 4]]]
3


In [117]:
arr=np.random.randint(1,50,3).reshape(1,3)
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)

[[33 24 44]]
2


In [133]:
# without randint it will generate the float random elements
arr=np.random.rand(10)
arr1=np.random.randint(10)
print(arr)
print(arr1)

[0.59577265 0.00510094 0.69444714 0.28717564 0.39843141 0.61487209
 0.27801384 0.79952067 0.18080081 0.20348093]
3


In [151]:
arr=np.random.random((10,5))
# print(arr)
# print(arr.ndim)

In [159]:
print(arr)
print("datatype:",arr.dtype)
print("dimension:",arr.ndim)
print("array_size:",arr.size)
print("shape:",arr.shape)

[[0.41718522 0.80011047 0.44216335 0.05022046 0.9153583 ]
 [0.95335324 0.66896519 0.59145354 0.8098071  0.73621277]]
datatype: float64
dimension: 2
array_size: 10
shape: (2, 5)


In [ ]:
arr=np.random.random(10).reshape(2,5)
# using the reshape function
print(arr)
print(arr.ndim)

[[0.41718522 0.80011047 0.44216335 0.05022046 0.9153583 ]
 [0.95335324 0.66896519 0.59145354 0.8098071  0.73621277]]
2


In [163]:
# flatten /ravel fuction :used to  convert  from 2D/3D array into 1 D array
arr1=arr.flatten()
print(arr1)

[0.41718522 0.80011047 0.44216335 0.05022046 0.9153583  0.95335324
 0.66896519 0.59145354 0.8098071  0.73621277]


In [162]:
arr1=arr.ravel()
print(arr1)

[0.41718522 0.80011047 0.44216335 0.05022046 0.9153583  0.95335324
 0.66896519 0.59145354 0.8098071  0.73621277]


In [173]:
l=[[2,3,45,23],[6,7,8,7]]
arr=np.array(l)
arr.shape
arr

array([[ 2,  3, 45, 23],
       [ 6,  7,  8,  7]])

In [178]:
# transpose means to cnvert row to column and vice versa
l=[[2,3,45,23],[6,7,8,7]]
arr=np.array(l)
arr.T.shape
print(arr.T)
# print(arr.transpose())

[[ 2  6]
 [ 3  7]
 [45  8]
 [23  7]]


In [166]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]
