In [274]:
import numpy as np
print("numpy is imported!")

numpy is imported!


In [275]:
lst1=[2,3,5,5,6]
print(lst1)

[2, 3, 5, 5, 6]


In [276]:
arr1=np.array([5,6,67,8,9])
print(arr1)
print(type(arr1))


[ 5  6 67  8  9]
<class 'numpy.ndarray'>


In [277]:
arr=np.array(lst1)
print(arr)
print(type(arr))


[2 3 5 5 6]
<class 'numpy.ndarray'>


In [278]:
lst=list(range(1,25))
print("list:",lst)
print(type(lst))
arr=np.array(lst)
print("array:",arr)
print(type(arr))

list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
<class 'list'>
array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
<class 'numpy.ndarray'>


list stored different kinds of datatypes where as array contains similar datatypes.

In [279]:
# creating array using np:
arr1=np.array([1,3,4,6])
arr1

array([1, 3, 4, 6])

In [280]:
# list
l=[3,34,5,2]
print(l)

[3, 34, 5, 2]


In [281]:
# build in module in python allow only integer values
r=range(0,25,2)
print(list(r))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]


In [282]:
# arrange() function:used only when np is imported and can be used for decimal and int values
arr=np.arange(1,25)
print(arr)
# 1 D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [283]:
# 2D array
arr=np.array([[2,3,5],[4,5,6]])
print(arr)
# to print the dimension of the arrays
print(arr.ndim)

[[2 3 5]
 [4 5 6]]
2


In [284]:
# 3 D array
arr=np.array([[[2,3,4],[4,5,6],[6,7,8]]])
print(arr)
# to print the dimension of the array
print(arr.ndim)

[[[2 3 4]
  [4 5 6]
  [6 7 8]]]
3


In [285]:
arr4=np.array([[[2,3,4,8],[4,5,6,8],[6,7,8,3]],[[2,3,4,6],[4,6,7,6],[6,7,8,9]]])
arr4

array([[[2, 3, 4, 8],
        [4, 5, 6, 8],
        [6, 7, 8, 3]],

       [[2, 3, 4, 6],
        [4, 6, 7, 6],
        [6, 7, 8, 9]]])

In [286]:
arr4.ndim

3

In [287]:

# zeros functions:to print the zero matrix
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [288]:
arr=np.ones(10)
print(arr)
# 1 D array

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [289]:
# ones functions
arr=np.ones((3,4))
print(arr)
print(arr.ndim)
# 2 D array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [290]:
# linspace functions:create a array with equal difference btw the given number
arr=np.linspace(1,10,5)
print(arr)
print(arr.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [291]:
# reshape is used to convert the dimension of the array from 1d array to 2d array
rs=np.linspace(1,10,5).reshape(5,1)
rs
print(rs.ndim)

2


In [292]:
arr=np.arange(0,30).reshape(2,15)
print(arr)
print(arr.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
2


In [293]:
arr.shape

(2, 15)

# 3 D array conversion 

In [294]:
arr=np.arange(0,30).reshape(5,6,1)
# 5:no of blocks
# 6 :rows
# 1:columns
print(arr)
print(arr.ndim)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]

 [[24]
  [25]
  [26]
  [27]
  [28]
  [29]]]
3


In [295]:
arr=np.arange(0,30).reshape(3,5,2)
print(arr)
print("dimension:",arr.ndim)
print("shape:",arr.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
dimension: 3
shape: (3, 5, 2)


In [296]:
# random initialization
arr=np.random.randint(50)
# 1-50 is the range 
# by default 1 
print(arr)

45


In [297]:
# random initialization
arr=np.random.randint(1,50)
# 1-50 is the range 
# by default 1 
print(arr)

30


In [298]:
arr=np.random.randint(1,50,(3,3))
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)
# 1 D array

[[26 16 14]
 [ 3  7  1]
 [ 5 23 16]]
2


In [299]:
arr=np.random.randint(1,50,3)
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)
# 1 D array


[30 14 20]
1


In [300]:
arr=np.random.randint(1,5,(3,3))
# coverting to 2 dim
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)

[[1 3 1]
 [2 2 1]
 [1 4 3]]
2


In [301]:
arr=np.random.randint(1,5,(3,3,3))
# coverting to 3 Dimension
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)

[[[1 3 2]
  [4 3 1]
  [2 1 4]]

 [[3 3 3]
  [2 3 3]
  [3 2 2]]

 [[4 1 1]
  [3 4 2]
  [1 1 3]]]
3


In [302]:
arr=np.random.randint(1,50,3).reshape(1,3)
# 3 means number of random elements we want.
print(arr)
print(arr.ndim)

[[20 44 24]]
2


In [303]:
# without randint it will generate the float random elements
arr=np.random.rand(10)
arr1=np.random.randint(10)
print(arr)
print(arr1)

[0.60509464 0.62437507 0.58500175 0.92266406 0.40704023 0.34550203
 0.27370613 0.71370191 0.7814348  0.32999652]
2


In [304]:
arr=np.random.random((10,5))
# print(arr)
# print(arr.ndim)

In [305]:
arr=np.arange(60)
# 1 D array h
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [306]:
arr=arr.reshape(12,5)
# reshape se 2D array mei convert krenge
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [307]:
# uski shape or dtype
print(arr.shape)
print(arr.dtype)

(12, 5)
int32


In [308]:
print(arr)
print("datatype:",arr.dtype)
print("dimension:",arr.ndim)
print("array_size:",arr.size)
print("shape:row and columns",arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]
datatype: int32
dimension: 2
array_size: 60
shape:row and columns (12, 5)


In [309]:
arr=np.random.random(10).reshape(2,5)
# using the reshape function
print(arr)
print(arr.ndim)

[[0.14760526 0.68803883 0.08504616 0.22331177 0.21111994]
 [0.68374718 0.73169959 0.22685605 0.2768498  0.04437946]]
2


In [310]:
# flatten /ravel fuction :used to  convert  from 2D/3D array into 1 D array
arr1=arr.flatten()
print(arr1)

[0.14760526 0.68803883 0.08504616 0.22331177 0.21111994 0.68374718
 0.73169959 0.22685605 0.2768498  0.04437946]


In [311]:
arr1=arr.ravel()
print(arr1)

[0.14760526 0.68803883 0.08504616 0.22331177 0.21111994 0.68374718
 0.73169959 0.22685605 0.2768498  0.04437946]


In [312]:
l=[[2,3,45,23],[6,7,8,7]]
arr=np.array(l)
print(arr.shape)
print(arr)

(2, 4)
[[ 2  3 45 23]
 [ 6  7  8  7]]


In [313]:
l=[[3,4,6,79],[3,5,7,9,23]]
print(len(l[0]))

4


In [314]:
arr

array([[ 2,  3, 45, 23],
       [ 6,  7,  8,  7]])

In [315]:
# transpose means to cnvert row to column and vice versa
l=[[2,3,45,23],[6,7,8,7]]
arr=np.array(l)
arr.T.shape
print(arr.T)
# print(arr.transpose())

[[ 2  6]
 [ 3  7]
 [45  8]
 [23  7]]


In [316]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [317]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [318]:
arr[2]

2

In [319]:
arr[4:10]
# arr slicing

array([4, 5, 6, 7, 8, 9])

In [320]:
arr[10:60]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [321]:
arr[10:70:2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58])

In [322]:
arr=np.arange(0,100).reshape(20,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [323]:
arr[14,2]
# 72 element accessing

72

In [324]:
arr[11,4]
# last element accessing

59

In [325]:
arr[11,-1]
# last element

59

In [326]:
arr[-1,-1]

99

In [327]:
arr[4,2]=210
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 210,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99]])

In [328]:
arr=np.arange(0,225)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [329]:
arr=arr.reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [330]:
# array replacement
arr[0][0]=23
print(arr)

[[[ 23  23  23]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]
  [120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]]

 [[135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]
  [150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 169 170]
  [171 172 173]
  [174 175 176]
  [177 178 179]]

 [[180 181 182]
  [183 184 185]


In [331]:
print(arr.shape)
print(arr.ndim)

(5, 15, 3)
3


In [332]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [333]:
arr[0][2:5][0]

array([6, 7, 8])

In [334]:
arr[:4][-1]

array([[135, 136, 137],
       [138, 139, 140],
       [141, 142, 143],
       [144, 145, 146],
       [147, 148, 149],
       [150, 151, 152],
       [153, 154, 155],
       [156, 157, 158],
       [159, 160, 161],
       [162, 163, 164],
       [165, 166, 167],
       [168, 169, 170],
       [171, 172, 173],
       [174, 175, 176],
       [177, 178, 179]])

In [335]:
arr[1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [336]:
arr[::-1]
# reverse

array([[[180, 181, 182],
        [183, 184, 185],
        [186, 187, 188],
        [189, 190, 191],
        [192, 193, 194],
        [195, 196, 197],
        [198, 199, 200],
        [201, 202, 203],
        [204, 205, 206],
        [207, 208, 209],
        [210, 211, 212],
        [213, 214, 215],
        [216, 217, 218],
        [219, 220, 221],
        [222, 223, 224]],

       [[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143],
        [144, 145, 146],
        [147, 148, 149],
        [150, 151, 152],
        [153, 154, 155],
        [156, 157, 158],
        [159, 160, 161],
        [162, 163, 164],
        [165, 166, 167],
        [168, 169, 170],
        [171, 172, 173],
        [174, 175, 176],
        [177, 178, 179]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [337]:
arr[11,4]

IndexError: index 11 is out of bounds for axis 0 with size 5

In [ ]:
arr[1,2]

7

In [ ]:
arr[1][2]

7

In [ ]:
arr[0:5]

array([[23,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[0:5,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [ ]:
arr[0:5,1:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [ ]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [ ]:
arr[2][3][1]=500

In [ ]:
arr +2
# 2 is added to every single element in the array

array([[[  2,   3,   4],
        [  5,   6,   7],
        [  8,   9,  10],
        [ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19],
        [ 20,  21,  22],
        [ 23,  24,  25],
        [ 26,  27,  28],
        [ 29,  30,  31],
        [ 32,  33,  34],
        [ 35,  36,  37],
        [ 38,  39,  40],
        [ 41,  42,  43],
        [ 44,  45,  46]],

       [[ 47,  48,  49],
        [ 50,  51,  52],
        [ 53,  54,  55],
        [ 56,  57,  58],
        [ 59,  60,  61],
        [ 62,  63,  64],
        [ 65,  66,  67],
        [ 68,  69,  70],
        [ 71,  72,  73],
        [ 74,  75,  76],
        [ 77,  78,  79],
        [ 80,  81,  82],
        [ 83,  84,  85],
        [ 86,  87,  88],
        [ 89,  90,  91]],

       [[ 92,  93,  94],
        [ 95,  96,  97],
        [ 98,  99, 100],
        [101, 502, 103],
        [104, 105, 106],
        [107, 108, 109],
        [110, 111, 112],
        [113, 114, 115],
        [116, 117, 118],
        [119, 120, 12

In [ ]:
arr -1

array([[[ -1,   0,   1],
        [  2,   3,   4],
        [  5,   6,   7],
        [  8,   9,  10],
        [ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19],
        [ 20,  21,  22],
        [ 23,  24,  25],
        [ 26,  27,  28],
        [ 29,  30,  31],
        [ 32,  33,  34],
        [ 35,  36,  37],
        [ 38,  39,  40],
        [ 41,  42,  43]],

       [[ 44,  45,  46],
        [ 47,  48,  49],
        [ 50,  51,  52],
        [ 53,  54,  55],
        [ 56,  57,  58],
        [ 59,  60,  61],
        [ 62,  63,  64],
        [ 65,  66,  67],
        [ 68,  69,  70],
        [ 71,  72,  73],
        [ 74,  75,  76],
        [ 77,  78,  79],
        [ 80,  81,  82],
        [ 83,  84,  85],
        [ 86,  87,  88]],

       [[ 89,  90,  91],
        [ 92,  93,  94],
        [ 95,  96,  97],
        [ 98, 499, 100],
        [101, 102, 103],
        [104, 105, 106],
        [107, 108, 109],
        [110, 111, 112],
        [113, 114, 115],
        [116, 117, 11

In [ ]:
arr *2

array([[[   0,    2,    4],
        [   6,    8,   10],
        [  12,   14,   16],
        [  18,   20,   22],
        [  24,   26,   28],
        [  30,   32,   34],
        [  36,   38,   40],
        [  42,   44,   46],
        [  48,   50,   52],
        [  54,   56,   58],
        [  60,   62,   64],
        [  66,   68,   70],
        [  72,   74,   76],
        [  78,   80,   82],
        [  84,   86,   88]],

       [[  90,   92,   94],
        [  96,   98,  100],
        [ 102,  104,  106],
        [ 108,  110,  112],
        [ 114,  116,  118],
        [ 120,  122,  124],
        [ 126,  128,  130],
        [ 132,  134,  136],
        [ 138,  140,  142],
        [ 144,  146,  148],
        [ 150,  152,  154],
        [ 156,  158,  160],
        [ 162,  164,  166],
        [ 168,  170,  172],
        [ 174,  176,  178]],

       [[ 180,  182,  184],
        [ 186,  188,  190],
        [ 192,  194,  196],
        [ 198, 1000,  202],
        [ 204,  206,  208],
        [ 210,  

In [ ]:
arr/2

array([[[  0. ,   0.5,   1. ],
        [  1.5,   2. ,   2.5],
        [  3. ,   3.5,   4. ],
        [  4.5,   5. ,   5.5],
        [  6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5],
        [  9. ,   9.5,  10. ],
        [ 10.5,  11. ,  11.5],
        [ 12. ,  12.5,  13. ],
        [ 13.5,  14. ,  14.5],
        [ 15. ,  15.5,  16. ],
        [ 16.5,  17. ,  17.5],
        [ 18. ,  18.5,  19. ],
        [ 19.5,  20. ,  20.5],
        [ 21. ,  21.5,  22. ]],

       [[ 22.5,  23. ,  23.5],
        [ 24. ,  24.5,  25. ],
        [ 25.5,  26. ,  26.5],
        [ 27. ,  27.5,  28. ],
        [ 28.5,  29. ,  29.5],
        [ 30. ,  30.5,  31. ],
        [ 31.5,  32. ,  32.5],
        [ 33. ,  33.5,  34. ],
        [ 34.5,  35. ,  35.5],
        [ 36. ,  36.5,  37. ],
        [ 37.5,  38. ,  38.5],
        [ 39. ,  39.5,  40. ],
        [ 40.5,  41. ,  41.5],
        [ 42. ,  42.5,  43. ],
        [ 43.5,  44. ,  44.5]],

       [[ 45. ,  45.5,  46. ],
        [ 46.5,  47. ,  47.5],
    

In [344]:
arr1=np.arange(60)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [345]:
arr2=np.arange(60)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [346]:
arr1+arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118])

In [347]:
arr1*arr2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481])

In [ ]:
x=[1,2,3,4,5]
y=[3,4,5,6,8]
x,y

([1, 2, 3, 4, 5], [3, 4, 5, 6, 8])

In [350]:
print(x+y)

[1, 2, 3, 4, 5, 3, 4, 5, 6, 8]


In [355]:
arrx=np.array(x)
arrx

array([1, 2, 3, 4, 5])

In [356]:
arry=np.array(y)
arry

array([3, 4, 5, 6, 8])

In [ ]:
arrx+arry
# list wla nhi hoga

array([ 4,  6,  8, 10, 13])

In [358]:
arrx*arry

array([ 3,  8, 15, 24, 40])

In [359]:
arrx/arry

array([0.33333333, 0.5       , 0.6       , 0.66666667, 0.625     ])